Update dotnet.yml
major change

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -18,16 +18,45 @@ jobs:
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 6.0.x
-    #- name: Trigger Workflow and Wait
-  #uses: convictional/trigger-workflow-and-wait@v1.6.5
+    
+    - name: Test
+      run: |
+        last_workflow=$(curl -X GET "https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches/runs" \
+          -H 'Accept: application/vnd.github.antiope-preview+json' \
+          -H "Authorization: Bearer $INPUT_GITHUB_TOKEN" | jq '[.workflow_runs[]] | first')
+        last_workflow_id=$(echo $last_workflow | jq '.id')
+        echo "The workflow id is [$last_workflow_id]."
+        echo ""
+        conclusion=$(echo $last_workflow | jq '.conclusion')
+        status=$(echo $last_workflow | jq '.status')
 
-    - uses: convictional/trigger-workflow-and-wait@v1.6.5
-      with:
-        owner: cmnawagamuwa
-        repo: AutomationWithGitHubAction
-        github_token: ${{ secrets.PAT_TOKEN }}
-        workflow_file_name: main.yml
-        ref: main
+        while [[ $conclusion == "null" && $status != "\"completed\"" ]]
+        do
+          echo "Sleeping for $wait_interval seconds"
+          sleep $wait_interval
+          workflow=$(curl -X GET "https://api.github.com/repos/cmnawagamuwa/AutomationWithGitHubAction/dispatches/runs" \
+            -H 'Accept: application/vnd.github.antiope-preview+json' \
+            -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" | jq '.workflow_runs[] | select(.id == '$last_workflow_id')')
+          conclusion=$(echo $workflow | jq '.conclusion')
+          status=$(echo $workflow | jq '.status')
+          echo "Checking conclusion [$conclusion]"
+          echo "Checking status [$status]"
+        done
+
+        if [[ $conclusion == "\"success\"" && $status == "\"completed\"" ]]
+        then
+          echo "Yes, success"
+        else
+          # Alternative "failure"
+          echo "Conclusion is not success, its [$conclusion]."
+          if [ "$propagate_failure" = true ]
+          then
+            echo "Propagating failure to upstream job"
+            exit 1
+          fi
+          fi
+
+  
     #- name: Test
     #  run: |
     #    curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
